apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: affine-migration
  name: affine-migration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: affine-migration
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: affine-migration
    spec:
      containers:
        - args:
            - sh
            - -c
            - node ./scripts/self-host-predeploy.js
          envFrom:
            - configMapRef:
                name: env
          image: ghcr.io/toeverything/affine:stable
          name: affine-migration-job
          volumeMounts:
            - mountPath: /root/.affine/storage
              name: affine-claim0
            - mountPath: /root/.affine/config
              name: affine-claim1
      restartPolicy: Always
      volumes:
        - name: affine-claim0
          persistentVolumeClaim:
            claimName: affine-claim0
        - name: affine-claim1
          persistentVolumeClaim:
            claimName: affine-claim1
