apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: affine-migration-claim1
  name: affine-migration-claim1
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
